mode_t defined in sys/types.h strncasecmp defined in strings.h scandir and alphasort require _BSD_SOURCE to be defined Make type conversions explicit
dirio.c(66): error: identifier "mode_t" is undefined
  static const mode_t DIR_MODE = S_IRWXU | S_IRWXG | S_IROTH | S_IXOTH;
               ^

dirio.c(198): warning #266: function "strncasecmp" declared implicitly
      int diff = strncasecmp(list->d_name, Pattern, Pattern_Len);
                 ^

dirio.c(198): warning #167: argument of type "const char *" is incompatible with parameter of type "void *"
      int diff = strncasecmp(list->d_name, Pattern, Pattern_Len);
                             ^

dirio.c(335): warning #266: function "scandir" declared implicitly
      int num = scandir (Input_Path, &Dir_List, match_pattern, alphasort);
                ^

dirio.c(335): error: identifier "alphasort" is undefined
      int num = scandir (Input_Path, &Dir_List, match_pattern, alphasort);
                                                               ^

dirio.c(547): warning #188: enumerated type mixed with another type
          Input_Format = matchidx;
                       ^

dirio.c(639): warning #188: enumerated type mixed with another type
      for (IOTYPE idx = 0; idx < E_NMATRIX; idx++) {
                        ^